# Generated by Django 4.2.7 on 2025-12-06 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR_USUARIO', 'Criação de usuário'), ('CRIAR_EVENTO', 'Cadastro de evento'), ('EDITAR_EVENTO', 'Alteração de evento'), ('EXCLUIR_EVENTO', 'Exclusão de evento'), ('INSCRICAO', 'Inscrição em evento'), ('CANCELAR_INSCRICAO', 'Cancelamento de inscrição'), ('EMITIR_CERTIFICADO', 'Emissão de certificado'), ('CONSULTAR_CERTIFICADO', 'Consulta de certificado'), ('API_CONSULTA', 'Consulta via API'), ('API_INSCRICAO', 'Inscrição via API')], help_text='Tipo de ação realizada', max_length=30)),
                ('descricao', models.TextField(help_text='Descrição detalhada da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP de origem', null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('dados_adicionais', models.JSONField(blank=True, help_text='Dados adicionais sobre a ação (JSON)', null=True)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner do evento (JPG, PNG, GIF, WEBP - máx 5MB)', null=True, upload_to='banners/%Y/%m/', validators=[eventos.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='evento',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Professor responsável pelo evento acadêmico', limit_choices_to={'perfil': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_como_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado',
            field=models.BooleanField(default=False, help_text='Indica se o email foi confirmado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_confirmacao',
            field=models.CharField(blank=True, help_text='Token para confirmação de email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(help_text='Telefone de contato no formato (XX) XXXXX-XXXX', max_length=20, validators=[eventos.validators.validate_phone_number]),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['ativo'], name='eventos_eve_ativo_999f2d_idx'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', 'data_hora'], name='eventos_aud_usuario_0e4b87_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['acao', 'data_hora'], name='eventos_aud_acao_a4a070_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['data_hora'], name='eventos_aud_data_ho_b6a10d_idx'),
        ),
    ]
