# Generated by Django 4.2.7 on 2025-12-12 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auditoria_evento_banner_evento_professor_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='professor_responsavel',
            field=models.ForeignKey(
                help_text='Professor responsável pelo evento acadêmico',
                limit_choices_to={'perfil': 'PROFESSOR'},
                on_delete=django.db.models.deletion.PROTECT,
                related_name='eventos_como_responsavel',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
